language: generic
sudo: false
git:
  depth: 10

os:
  - linux
  - osx

before_script:
  - git clone --depth=1 --single-branch https://github.com/thinca/vim-themis /tmp/vim-themis

script:
  - vim --version
  - /tmp/vim-themis/bin/themis
